name: getvuapp
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  cool_dropdown: ^1.4.2
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_login: ^4.0.0
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_maps_flutter: ^2.2.1
  persistent_bottom_nav_bar: ^5.0.2
  razorpay_flutter: ^1.3.4

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/Images/
